src/steadystate.jl
The steadystate.eigen(L) function previously took the eigenvector of the first eigenvalue which is not necessarily the one closest to zero; fixed by finding the minimum of the absolute values.
=> Fixed steadystate eigen for DenseOperators

docs/source/conf.py
When I followed the available instructions to build the documentation (i.e. cloning the `gh-pages` branch as described an installing your `sphinx-julia` package) I ran into the following error:
```
>> make html
sphinx-build -b html -d build/doctrees   source ../../QuantumOptics.jl-docs/html
Running Sphinx v1.4.6
WARNING: the config value 'copyright' is set to a string with non-ASCII characters; this can lead to Unicode errors occurring. Please use Unicode strings, e.g. u'Content'.
PyJulia not found - using slower alternative.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
Encoding error:
'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-UOKOhp.log, if you want …
```
=> Fix encoding error when using sphinx to build docs

examples/lazy.jl, examples/particle.jl, examples/particle2d.jl, examples/pumpedcavity.jl, examples/pumpedspin.jl, examples/raman.jl, examples/v-atom-cavity.jl
I added two example scripts for three-level atoms. While I was at it, I noticed that many of the `.jl` examples still had `using quantumoptics` instead of `QuantumOptics`, so I changed that as well. @bastikr please review and merge.
=> Nlevel examples

src/steadystate.jl
I ran into a problem when using the function `steadystate.eigenvector(L::DenseSuperOperator)`. It was producing wrong results. Digging around a bit and comparing it to the analogous function for sparse operators - which gave correct results - I found that the trace normalization was missing for dense operators.
=> Add trace norm to eigenvector function for dense operators

README.rst
The readme will be more thoroughly updated in the upcoming update of the documentation. For now, following issue #35 I simply changed the link addresses.
=> Change links to docs to correct address

src/operators_dense.jl, src/operators_sparse.jl, test/test_operators.jl, test/test_sparseoperators.jl
Instead of calculating the whole matrix A*B first calculate only the
diagonal entries.
=> Faster calculation of expectation values.

src/states.jl
Missing parameter constraint means it was implemented for all types.
=> Fix bug in copy() for state vectors.

src/metrics.jl, test/test_metrics.jl
Remove factor 1/2 from the trace norm definition and add this factor to
the definition of the trace distance.
=> Fix definition of tracenorm.

src/timecorrelations.jl
When doing some analytics, I realized that the relation we used to write the spectrum as the real part of the integral does not hold, in general, for quantized fields. The common approach seems to be to write the spectrum as real part using the classical counter-part and then replace the fields by operators (see, for example, _Mathematical Methods of Quantum Optics, R.R. Puri_). I think it would be best to only ever mention the definition of the spectrum with the real part.
=> Remove part of definition of spectrum in docstrings

src/mcwf.jl, test/test_timeevolution_mcwf.jl
I have changed the syntax of `timeevolution.mcwf` to accept the kwarg `rates` as in `timeevolution.master`.
It now accepts `rates` as a vector of floats of the same length as `J`. I also thought about implementing an internal diagonalization, such that if `rates` is a matrix, a new set of jump operators and rates is calculated using `diagonljumps`. However, since usually one computes many trajectories using the MCWF method, this would be expensive as the calculation is repeated for every trajectory. Instead, `timeevolution.mcwf` now throws an error if `rates` is a matrix, which points the user towards using `diagonaljumps` a priori.
The same changes were made to `mcwf_h`, but not `mcwf_nh`. I don't see why anyone would use `mcwf_nh` instead of `mcwf` if the rates are not already included …
=> Change interface of mcwf to match that of master

src/bases.jl, test/test_bases.jl
This way they are the same object (as intended I think?) and they share the same documentation string.
=> Equate ⊗ with `tensor`

src/operators_sparse.jl
Used to throw an `AssertionError`
=> Fix bug in diagonaloperator so it accepts composite bases

.travis.yml, README.md, REQUIRE, appveyor.yml, src/mcwf.jl, src/steadystate.jl, src/timecorrelations.jl, src/timeevolution_base.jl, test/test_steadystate.jl, test/test_timeevolution_schroedinger.jl
This sets up the internals to use DiffEq. All of the tests pass. There is a breaking change in that the steady state parts now return the solution array (with saveat matching the giving timespan, so it's the same but includes the initial point). Other than that, nothing changes. This requires DiffEqCallbacks v0.7.0 which should be released shortly.
As for speed, benchmarks show that as setup it's roughly the same on very non-stiff problems. The previous integrator's `reltol=1e-7` takes as much steps as this one's `reltol=1e-6`, and with these the DiffEq one is ever so slightly faster. But true benchmarks should take into account error as well. The QO benchmarks should be run again like in https://github.com/qojulia/QuantumOptics.jl/issues/92 . Note that the current DiffEq infrusturcture …
=> Change internals to Diffeq

src/particle.jl, test/test_particle.jl, test/test_printing.jl
This should implement all functionality required to solve #190.
Some more comments:
- Benchmarks need to be run once more.
- This is not a lazy implementation, but using `ket_only` makes it as efficient as saving a `Ket`. Going below this is only relevant if one is neglecting correlations.
- Things might not be entirely type stable here, so there might be some clean-up work to do.
- Using an `FFTOperator` in a `LazyTensor` will still throw the error as in #190. However, this can be avoided by rewriting things to a `LazyProduct`. We should maybe consider making this rewriting automatic or at least provide a more helpful error message.
EDIT:
Also, more rigorous tests are necessary.
=> Generalization of FFTOperator to composite bases

src/steadystate.jl, src/timecorrelations.jl, src/timeevolution_base.jl, test/test_steadystate.jl, test/test_timecorrelations.jl
This fixes a small bug that was caused by a missing definition of `eps` in `steadystate.master`. However, it was a bit tough to track down since `eps` is a function in `Base`. To avoid things like this in the future, all occurrences of `eps` have been renamed to `tol`.
=> Fix bug in steady-state and rename eps to tol everywhere

REQUIRE, src/mcwf.jl, test/test_timeevolution_mcwf.jl
For reference: the bug is related to this issue https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/issues/30
Once that is resolved, we can clean up the source code accordingly.
=> Fix bug in MCWF that prevented saving before/after jumps

src/QuantumOptics.jl, src/printing.jl, test/test_printing.jl
I inverse the order of the subsystems, to get the standard output for tensor products. It's an easy fix for the problem.
Because rounding errors clutter the output for large matrices I round them to zero.
The data representation is unchanged with .data. It just changes the output for bra/ket and sparse/dense operators.
=> Address Issue "Odd convention for the tensor product? "

src/operators_sparse.jl
Variable `rank` isn't used anywhere.
=> remove unnecessary rank calculation

src/printing.jl, test/test_printing.jl
I have improved standard order printing by removing permutation.
As far as I know, there are two issues related to standard order printing.
- As increasing dimensions, permutation can't work correctly at a certain point.
- It takes a lot of time to print for high dimensional state.
```julia
julia> using QuantumOptics
julia> QuantumOptics.set_printing(standard_order=false)
julia> n = 16;
julia> state = randstate(tensor([SpinBasis(1//2) for i in 1:n]...))
Ket(dim=65536)
basis: [Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2) ⊗ Spin(1/2)]
0.00356055+0.00413365im
0.00125937+0.000968859im
0.0037847+0.000102558im
0.00148401+0.00277967im
0.00431765+0.00336918im …
```
=> Improve standard order printing

src/operators_dense.jl, src/operators_sparse.jl, test/test_operators_dense.jl, test/test_operators_sparse.jl
If an operator is Hermitian, both left and right bases should be same.
=> fix ishermitian for dense and sparse operator

src/steadystate.jl, test/test_steadystate.jl
@vtorggler is this okay now or are further changes required?
=> Change steady state sorting

src/operators.jl, test/test_operators.jl, test/test_operators_dense.jl
This is useful and makes sense mathematically, especially
now that the meaning of `'` has been clarified as `adjoint`.
=> Define ' on Operator as dagger()

src/particle.jl
The fftoperators had Array{ComplexF64} which is an abstract type, making gemv! type unstable
=> Added parameter to FFToperators so the gemv! is type stable

src/operators.jl, src/operators_sparse.jl, src/sortedindices.jl, test/test_operators.jl, test/test_sortedindices.jl
=> before embedding check that the destination basis matches the operator basis

Project.toml, src/steadystate.jl
ARPACKException is no longer defined in LinearAlgebra but instead in Arpack.jl (https://github.com/JuliaLinearAlgebra/Arpack.jl/pull/65).
This fixes the tests in the package on 1.3
=> use ARPACKException from Arpack.jl

src/bloch_redfield_master.jl
Added some more concrete types and type stability fixes and cleaned up the main loop in the timeevolution.bloch_redfield_tensor function to increase efficiency.
This function is still the main bottleneck in my project and it seems like the main loop is still the most time consuming part of the function so I did look into parallelizing the loop but couldn't settle on a implementation I was happy with so have removed it for now. I may have another go at this in the future.
=> Improved-BR-tensor

src/bloch_redfield_master.jl
Fixed bug in the case where no interaction operators were specified (should really just use liouvillian instead of bloch_redfield_tensor in that case anyway).
=> Small bug fix

Project.toml, src/phasespace.jl, test/test_phasespace.jl
To go along with https://github.com/qojulia/QuantumOpticsBase.jl/pull/14. The `wigner` function still needs to be updated, which could be tricky.
=> Update phase-space methods for offsets in FockBasis

Project.toml, src/QuantumOptics.jl, src/phasespace.jl
This is to accommodate the changes proposed in qojulia/QuantumOpticsBase.jl#15.
Added imports from QuantumOpticsBase.jl of phase space functions.
=> Phase space functions declaration moved in QuantumOpticsBase.jl

src/master.jl, src/mcwf.jl, src/stochastic_master.jl
This fixes an `InexactError` when trying to solve a master equation where `eltype(H) <: Real` as mentioned in [https://github.com/qojulia/QuantumOpticsBase.jl/pull/18](https://github.com/qojulia/QuantumOpticsBase.jl/pull/18). The issue is cause by calling `eltype(H)(0.5im)` which tries to convert `0.5im` to a real number.
I can see that similar calls to `eltype(::Operator)(im)` exist in other places such as here:
https://github.com/qojulia/QuantumOptics.jl/blob/e8a3ed060278bb7e4790474053cbe06ce55d656e/src/schroedinger.jl#L57-L60
which looks like it will fail if the initial state `psi0` given to `schoedinger` is real, but I don't know enough about these other sections of the code base to know if they are issues that need fixed.
At the moment, all convenience functions such as `fockstate`, …
=> Allow real Hamiltonians in master and stochastic_master

src/timecorrelations.jl, test/test_timecorrelations.jl
Add function for computing two-time correlations for time-dependent master equation.
=> Add function correlation_dynamic

src/phasespace.jl, test/test_phasespace.jl
This uses a recursive formula for the binomial coefficient in the construction of a `coherentspinstate` in order to avoid the overflow associated with the built-in `binomial` for larger values of S
Closes #326
=> Use recursive formula for binomial coefficient in CSS construction

src/schroedinger.jl, test/test_timeevolution_schroedinger.jl
dynamics of Operator with different left and right basis would fail.
for example;
```
b1 = FockBasis(4)
b2 = NLevelBasis(2)
H(t,u) = number(b1) + destroy(b1) + create(b1)
ψ0 = projector(b1, SubspaceBasis(b1,[basisstate.([b1],1:2)...]))
ψ1 = Operator(ψ0.basis_l, FockBasis(1), ψ0.data)
timeevolution.schroedinger_dynamic(range(0,1,10), ψ1, H); # ok
timeevolution.schroedinger_dynamic(range(0,1,10), ψ0, H); # fail
```
`recast!` of an Operator type with different left and right basis fixes this.
This is useful for propagating a subset of states.
=> added method for recast!

Project.toml, test/test_steadystate.jl
Error for Arpack.jl version 0.5.4 in the docu example [Optomechanical cooling](https://docs.qojulia.org/examples/optomech-cooling/).
=> restricted Arpack version

src/schroedinger.jl, test/test_timeevolution_schroedinger.jl
Similar to https://github.com/qojulia/QuantumOptics.jl/pull/340.
Allow Operators with different left and right basis to propagate with `schroedinger` + tests.
Also, update this in the doc string of `schroedinger` and `schroedinger_dynamics`. Is the wording clear enough?
=> Propagating operators with schroedinger

src/QuantumOptics.jl, src/master.jl, src/mcwf.jl, src/schroedinger.jl, src/time_dependent_operators.jl, test/runtests.jl, test/test_timeevolution_tdops.jl
This accompanies https://github.com/qojulia/QuantumOpticsBase.jl/pull/104. Tests won't pass until those changes are included.
Provides methods for "dynamic" time evolution that take time-dependent operators directly.
=> Support time-dependent operators in timeevolution

src/time_dependent_operators.jl
Calling the operator itself will become slow if https://github.com/qojulia/QuantumOpticsBase.jl/pull/124 is merged.
=> Only use set_time! for tdop updates

src/schroedinger.jl, test/test_ForwardDiff.jl
Issue https://github.com/qojulia/QuantumOptics.jl/issues/376
=> Promote TimeDependentSum to Dual when using ForwardDiff

Project.toml, src/QuantumOptics.jl, src/debug.jl, src/master.jl
I added hints for master and Schrödinger solver when there is a `MethodError`. I also referenced master_dynamic in the `see also` section of the master. https://github.com/qojulia/QuantumOptics.jl/issues/386
=> Adding hint for master and Schrödinger solver

src/bloch_redfield_master.jl, src/master.jl, src/mcwf.jl, src/schroedinger.jl, src/semiclassical.jl, src/timeevolution_base.jl
This PR does two things:
* Uses `let` blocks around inner function definitions to avoid boxing of closure variables.
* Uses type parameters for function/callable types in some places to encourage specialization.
User-visible changes should be:
* It is possible to use more generic callable types in some places where `Function` types were previously required.
* Parts of MCWF evolution are stabilized and made allocation free, so MCWF evolution should no longer allocate on each call to the integrand.
=> Inference improvements for timeevolution

src/time_dependent_operators.jl, test/test_timeevolution_tdops.jl
Requires https://github.com/qojulia/QuantumOpticsBase.jl/pull/171 to make allocs test pass.
=> Don't tuplify time-dependent ops if types are homogenous

Project.toml, src/timeevolution_base.jl
Quick workaround for incompatibility with recent DiffEqBase.
Closes #433
=> Quick fix for promote dual

src/master.jl
Correct typo in function signature in docstring for master_nh_dynamic to match the actual function.
=> Correct docstring typo in master.jl
